spring:
  profile.active: dev, test, prod
  datasource:
    url: jdbc:mysql://${DB_HOST}/vollmed_api
    username: root
    password: Thelastelement22
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET:45632710}

#spring.datasource.url=jdbc:mysql://localhost/vollmed_api
#spring.datasource.username=root
#spring.datasource.password=2812
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#server.error.include-stacktrace=never
#
#api.security.secret=${JWT_SECRET:123456}

